### ISSUE TITLE
VK-url-scraper: errors and requirement of kernel reload when running in colab

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/open-source-research-notebooks#25]
Currently, running the `!pip install vk-url-scraper` cell in Google Colab results in pip error messages in the notebook, it would be great if the requirements were tweaked to avoid these errors, or the output of the install is piped to a log file to not worry the user.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[...]

WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit, pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Disconnect and delete runtime" from the "Runtime" menu.

WARNING: The following packages were previously imported in this runtime:
  [cffi,jaraco,tornado]
You must restart the runtime in order to use newly installed versions.
```

**Comment by msramalho** [comment]
If the reload message appears it should be reloaded so I would not opt to hide the message straight away but rather add a warning if the issue has not been solved.

As for fixing it, I doubt it could be easily done in a sustainable way. Colab under-the-hood dependencies can change (both the deps as well as their versions) and modifying vk-url-scraper in order to accommodate colab does not make sense to me, if it's even possible without breaking vk-url-scraper.
